
import br.ufrn.dca.controle.QuanserClient;
import br.ufrn.dca.controle.QuanserClientException;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.SwingConstants;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Geraldo
 */
/**
 * Biblioteca necessárias: QuanserCliente.jar jcommon-1.0.23 jfreechart-1.0.19
 * jfreechart-1.0.19-swt
 */
public class Main extends javax.swing.JFrame {
    
    
    private double nivelTanque1 = 0;
    private double nivelTanque2 = 0;
    
    private double tensaoTanque1 = 0;
    private double tensaoTanque2 = 0;

    private double pv;

    XYSeries series = new XYSeries("Gráfico");

    private double x = 0;

    private int amplitude;
    private int amplitudeMax;
    private int amplitudeMin;
    private double frequencia;
    private double periodo;

    /*Tipos de ondas possiveis*/
    public static final int DEGRAU = 10;
    public static final int ONDA_SENOIDAL = 20;
    public static final int ONDA_QUADRADA = 30;
    public static final int DENTE_DE_SERRA = 40;
    public static final int SINAL_ALEATORIO = 50;

    private int sinalAtual = -1;

    /*Informa qual  radioButton está selecionado*/
    private int radioSelecionado = -1;

    /*Informa quais  e quantos CheckButtons está selecionado*/
    private List<Integer> checkSelecionado = new ArrayList<Integer>();

    /*Quantos podem ser selecionados ? */
    private int qtdCheckSelecionado = 3;

    /*Verifica se é malha aberta*/
    private boolean isMalhaAberta = true;

    private int offSet = 0;

    private QuanserClient qClient;

    public Main() {
        //ao iniciar a Frame já faz a conexão
        try {
            qClient = new QuanserClient("10.13.99.69", 20081);
        } catch (QuanserClientException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "A conexão falhou");
        }
        initComponents();
        //jProgressBar1.setOrientation(JProgressBar.HORIZONTAL);
        criandoGrafico(0,0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRadioButton = new javax.swing.ButtonGroup();
        buttonGroupMalha = new javax.swing.ButtonGroup();
        buttonGroupTipoOnda = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Leitura"));
        jPanel1.setName(""); // NOI18N

        jCheckBox1.setText("01");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("02");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("03");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("04");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setText("05");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox6.setText("06");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jCheckBox7.setText("07");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox7))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Escrita"));

        buttonGroupRadioButton.add(jRadioButton1);
        jRadioButton1.setText("01");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroupRadioButton.add(jRadioButton2);
        jRadioButton2.setText("02");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroupRadioButton.add(jRadioButton3);
        jRadioButton3.setText("03");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroupRadioButton.add(jRadioButton4);
        jRadioButton4.setText("04");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        buttonGroupRadioButton.add(jRadioButton5);
        jRadioButton5.setText("05");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        buttonGroupRadioButton.add(jRadioButton6);
        jRadioButton6.setText("06");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        buttonGroupRadioButton.add(jRadioButton7);
        jRadioButton7.setText("07");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton7)
                .addGap(215, 215, 215))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        buttonGroupMalha.add(jRadioButton8);
        jRadioButton8.setSelected(true);
        jRadioButton8.setText("Malha Aberta");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        buttonGroupMalha.add(jRadioButton9);
        jRadioButton9.setText("Malha Fechada");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jRadioButton8)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton9))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo Sinal"));

        buttonGroupTipoOnda.add(jRadioButton10);
        jRadioButton10.setText("Degrau");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });

        buttonGroupTipoOnda.add(jRadioButton11);
        jRadioButton11.setText("Onda Senoidal");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });

        buttonGroupTipoOnda.add(jRadioButton12);
        jRadioButton12.setText("Onda Quadrada");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });

        buttonGroupTipoOnda.add(jRadioButton13);
        jRadioButton13.setText("Dente de Serra");
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });

        buttonGroupTipoOnda.add(jRadioButton14);
        jRadioButton14.setText("Sinal Aleatorio");
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });

        jLabel1.setText("Amplitude");

        jLabel2.setText("Duração");

        jSpinner3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner3StateChanged(evt);
            }
        });

        jSpinner4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner4StateChanged(evt);
            }
        });

        jSpinner5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner5StateChanged(evt);
            }
        });

        jLabel5.setText("Frequência/Periodo");

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });

        jLabel6.setText("Offset");

        jTextField3.setText("0");
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSpinner4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jRadioButton14, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton14)
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Gráficos"));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Nivel 1                                Nivel 2"));

        jProgressBar1.setMaximum(30);
        jProgressBar1.setValue(15);

        jProgressBar2.setMaximum(30);
        jProgressBar2.setValue(15);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jProgressBar1.setOrientation(JProgressBar.VERTICAL);
        jProgressBar2.setOrientation(JProgressBar.VERTICAL);

        jToggleButton1.setText("Start");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToggleButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(208, 208, 208)))
                        .addContainerGap())
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton1.isSelected()) {
            radioSelecionado = 1;
        }

        System.out.print(radioSelecionado);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if (jRadioButton2.isSelected()) {
            radioSelecionado = 2;
        }
        System.out.print(radioSelecionado);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton3.isSelected()) {
            radioSelecionado = 3;
        }
        System.out.print(radioSelecionado);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton4.isSelected()) {
            radioSelecionado = 4;
        }
        System.out.print(radioSelecionado);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton5.isSelected()) {
            radioSelecionado = 5;
        }
        System.out.print(radioSelecionado);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton6.isSelected()) {
            radioSelecionado = 6;
        }
        System.out.print(radioSelecionado);
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton7.isSelected()) {
            radioSelecionado = 7;
        }
        System.out.print(radioSelecionado);
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            if (qtdCheckSelecionado > 0) {
                checkSelecionado.add(1);
                qtdCheckSelecionado = qtdCheckSelecionado - 1;
                System.out.print(checkSelecionado.size() + " " + qtdCheckSelecionado);
            } else {
                jCheckBox1.setSelected(false);
                JOptionPane.showMessageDialog(null, "Limite Atingido!");
            }

        } else //verifica se aquele elemento está na lista
        {
            if (checkSelecionado.contains(1)) {
                checkSelecionado.remove(checkSelecionado.indexOf(1));
                qtdCheckSelecionado += 1;
                System.out.print(checkSelecionado.size() + "" + qtdCheckSelecionado);
            }
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox2.isSelected()) {
            if (qtdCheckSelecionado > 0) {
                checkSelecionado.add(2);
                qtdCheckSelecionado = qtdCheckSelecionado - 1;
                System.out.print(checkSelecionado.size() + " " + qtdCheckSelecionado);
            } else {
                jCheckBox2.setSelected(false);
                JOptionPane.showMessageDialog(null, "Limite Atingido!");
            }

        } else //verifica se aquele elemento está na lista
        {
            if (checkSelecionado.contains(2)) {
                checkSelecionado.remove(checkSelecionado.indexOf(2));
                qtdCheckSelecionado += 1;
                System.out.print(checkSelecionado.size() + "" + qtdCheckSelecionado);
            }
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox3.isSelected()) {
            if (qtdCheckSelecionado > 0) {
                checkSelecionado.add(3);
                qtdCheckSelecionado = qtdCheckSelecionado - 1;
                System.out.print(checkSelecionado.size() + " " + qtdCheckSelecionado);
            } else {
                jCheckBox3.setSelected(false);
                JOptionPane.showMessageDialog(null, "Limite Atingido!");
            }

        } else //verifica se aquele elemento está na lista
        {
            if (checkSelecionado.contains(3)) {
                checkSelecionado.remove(checkSelecionado.indexOf(3));
                qtdCheckSelecionado += 1;
                System.out.print(checkSelecionado.size() + "" + qtdCheckSelecionado);
            }
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox4.isSelected()) {
            if (qtdCheckSelecionado > 0) {
                checkSelecionado.add(4);
                qtdCheckSelecionado = qtdCheckSelecionado - 1;
                System.out.print(checkSelecionado.size() + " " + qtdCheckSelecionado);
            } else {
                jCheckBox4.setSelected(false);
                JOptionPane.showMessageDialog(null, "Limite Atingido!");
            }

        } else //verifica se aquele elemento está na lista
        {
            if (checkSelecionado.contains(4)) {
                checkSelecionado.remove(checkSelecionado.indexOf(4));
                qtdCheckSelecionado += 1;
                System.out.print(checkSelecionado.size() + "" + qtdCheckSelecionado);
            }
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox5.isSelected()) {
            if (qtdCheckSelecionado > 0) {
                checkSelecionado.add(5);
                qtdCheckSelecionado = qtdCheckSelecionado - 1;
                System.out.print(checkSelecionado.size() + " " + qtdCheckSelecionado);
            } else {
                jCheckBox5.setSelected(false);
                JOptionPane.showMessageDialog(null, "Limite Atingido!");
            }

        } else //verifica se aquele elemento está na lista
        {
            if (checkSelecionado.contains(5)) {
                checkSelecionado.remove(checkSelecionado.indexOf(5));
                qtdCheckSelecionado += 1;
                System.out.print(checkSelecionado.size() + "" + qtdCheckSelecionado);
            }
        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox6.isSelected()) {
            if (qtdCheckSelecionado > 0) {
                checkSelecionado.add(6);
                qtdCheckSelecionado = qtdCheckSelecionado - 1;
                System.out.print(checkSelecionado.size() + " " + qtdCheckSelecionado);
            } else {
                jCheckBox6.setSelected(false);
                JOptionPane.showMessageDialog(null, "Limite Atingido!");
            }

        } else //verifica se aquele elemento está na lista
        {
            if (checkSelecionado.contains(6)) {
                checkSelecionado.remove(checkSelecionado.indexOf(6));
                qtdCheckSelecionado += 1;
                System.out.print(checkSelecionado.size() + "" + qtdCheckSelecionado);
            }
        }
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox7.isSelected()) {
            if (qtdCheckSelecionado > 0) {
                checkSelecionado.add(7);
                qtdCheckSelecionado = qtdCheckSelecionado - 1;
                System.out.print(checkSelecionado.size() + " " + qtdCheckSelecionado);
            } else {
                jCheckBox7.setSelected(false);
                JOptionPane.showMessageDialog(null, "Limite Atingido!");

            }

        } else //verifica se aquele elemento está na lista
        {
            if (checkSelecionado.contains(7)) {
                checkSelecionado.remove(checkSelecionado.indexOf(7));
                qtdCheckSelecionado += 1;
                System.out.print(checkSelecionado.size() + "" + qtdCheckSelecionado);
            }
        }
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton8.isSelected()) {
            isMalhaAberta = true;
        }
        System.out.print(isMalhaAberta);
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton9.isSelected()) {
            isMalhaAberta = false;
        }
        System.out.print(isMalhaAberta);
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton10.isSelected()) {
            sinalAtual = DEGRAU;
        }
        jSpinner5.setVisible(true);
        jSpinner1.setVisible(false);
        jSpinner2.setVisible(false);
        jSpinner3.setVisible(false);
        jSpinner4.setVisible(false);
        jLabel2.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton11.isSelected()) {
            sinalAtual = ONDA_SENOIDAL;
        }
        jLabel1.setVisible(true);
        jSpinner5.setVisible(true);
        jSpinner1.setVisible(false);
        jSpinner2.setVisible(false);
        jSpinner3.setVisible(false);
        jSpinner4.setVisible(false);
        jLabel2.setVisible(false);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);

    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton12.isSelected()) {
            sinalAtual = ONDA_QUADRADA;
        }
        jLabel1.setVisible(true);
        jSpinner5.setVisible(true);
        jSpinner1.setVisible(false);
        jSpinner2.setVisible(false);
        jSpinner3.setVisible(false);
        jSpinner4.setVisible(false);
        jLabel2.setVisible(false);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);

    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton13.isSelected()) {
            sinalAtual = DENTE_DE_SERRA;
        }
        jLabel1.setVisible(true);
        jSpinner5.setVisible(true);
        jSpinner1.setVisible(false);
        jSpinner2.setVisible(false);
        jSpinner3.setVisible(false);
        jSpinner4.setVisible(false);
        jLabel2.setVisible(false);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);

    }//GEN-LAST:event_jRadioButton13ActionPerformed

    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton14.isSelected()) {
            sinalAtual = SINAL_ALEATORIO;
        }
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jSpinner1.setVisible(true);
        jSpinner2.setVisible(true);
        jSpinner3.setVisible(true);
        jSpinner4.setVisible(true);
        jSpinner5.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
    }//GEN-LAST:event_jRadioButton14ActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        if (isMalhaAberta && sinalAtual == SINAL_ALEATORIO) {
            //valor minimo
            if (Integer.parseInt(jSpinner1.getValue().toString()) > 4 | Integer.parseInt(jSpinner1.getValue().toString()) < -4) {
                //pegar um numero ramdomico 
                if (Integer.parseInt(jSpinner1.getValue().toString()) > 4) {
                    jSpinner1.setValue(4);
                } else {
                    jSpinner1.setValue(-4);
                }
                JOptionPane.showMessageDialog(null, "limite ultrapassado");
            } else {
                amplitudeMin = Integer.parseInt(jSpinner1.getValue().toString());
            }
        }
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner2StateChanged
        // TODO add your handling code here:
        if (isMalhaAberta && sinalAtual == SINAL_ALEATORIO) {
            //valor minimo
            if (Integer.parseInt(jSpinner2.getValue().toString()) > 4 | Integer.parseInt(jSpinner2.getValue().toString()) < -4) {
                //pegar um numero ramdomico 
                if (Integer.parseInt(jSpinner2.getValue().toString()) > 4) {
                    jSpinner2.setValue(4);
                } else {
                    jSpinner2.setValue(-4);
                }
                JOptionPane.showMessageDialog(null, "limite ultrapassado");
            } else {
                amplitudeMax = Integer.parseInt(jSpinner2.getValue().toString());
            }
        }
    }//GEN-LAST:event_jSpinner2StateChanged

    private void jSpinner5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner5StateChanged
        // TODO add your handling code here:
        if (isMalhaAberta && sinalAtual != SINAL_ALEATORIO) {
            //valor minimo
            if (Integer.parseInt(jSpinner5.getValue().toString()) > 4 | Integer.parseInt(jSpinner5.getValue().toString()) < -4) {
                //pegar um numero ramdomico 
                if (Integer.parseInt(jSpinner5.getValue().toString()) > 4) {
                    jSpinner5.setValue(4);
                } else {
                    jSpinner5.setValue(-4);
                }
                JOptionPane.showMessageDialog(null, "limite ultrapassado");
            } else {
                amplitude = Integer.parseInt(jSpinner5.getValue().toString());
            }
        } else if (!isMalhaAberta && sinalAtual != SINAL_ALEATORIO) {
            if (Integer.parseInt(jSpinner5.getValue().toString()) > 30 | Integer.parseInt(jSpinner5.getValue().toString()) < 0) {
                //pegar um numero ramdomico 
                if (Integer.parseInt(jSpinner5.getValue().toString()) > 30) {
                    jSpinner5.setValue(30);
                } else {
                    jSpinner5.setValue(0);
                }
                JOptionPane.showMessageDialog(null, "limite ultrapassado");
            } else {
                amplitude = Integer.parseInt(jSpinner5.getValue().toString());
            }
        }
    }//GEN-LAST:event_jSpinner5StateChanged

    private void jSpinner4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner4StateChanged
        // TODO add your handling code here:
        if (isMalhaAberta && sinalAtual == SINAL_ALEATORIO) {
            //valor minimo
            if (Integer.parseInt(jSpinner4.getValue().toString()) > 60 | Integer.parseInt(jSpinner4.getValue().toString()) < 0) {
                //pegar um numero ramdomico 
                if (Integer.parseInt(jSpinner4.getValue().toString()) > 60) {
                    jSpinner4.setValue(60);
                } else {
                    jSpinner4.setValue(0);
                }
                JOptionPane.showMessageDialog(null, "limite ultrapassado");
            }
        }
    }//GEN-LAST:event_jSpinner4StateChanged

    private void jSpinner3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner3StateChanged
        // TODO add your handling code here:
        if (isMalhaAberta && sinalAtual == SINAL_ALEATORIO) {
            //valor minimo
            if (Integer.parseInt(jSpinner3.getValue().toString()) > 60 | Integer.parseInt(jSpinner3.getValue().toString()) < 0) {
                //pegar um numero ramdomico 
                if (Integer.parseInt(jSpinner3.getValue().toString()) > 60) {
                    jSpinner3.setValue(60);
                } else {
                    jSpinner3.setValue(0);
                }
                JOptionPane.showMessageDialog(null, "limite ultrapassado");
            }
        }
    }//GEN-LAST:event_jSpinner3StateChanged

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        String erro = "";
        if (jToggleButton1.isSelected()) {
            //quando o usuário da start
            jToggleButton1.setText("Stop");
            //valida no caso sinal aleatorio 
            if (sinalAtual == SINAL_ALEATORIO && amplitudeMax < amplitudeMin) {
                JOptionPane.showMessageDialog(null, "Amplitude Max < Amplitude Min");
            }
            //validando campos vázios ou não selecionados
            if (sinalAtual < 0) {
                erro = erro + "Tipo Sinal";
            } else if (sinalAtual == ONDA_QUADRADA || sinalAtual == ONDA_SENOIDAL || sinalAtual == DENTE_DE_SERRA) {
                if (jTextField1.getText().isEmpty()) {
                    erro = ", Periodo";
                } else {
                    try {
                        periodo = Double.parseDouble(jTextField1.getText());
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Período: formato inválido");
                    }
                }
                if (jTextField2.getText().isEmpty()) {
                    erro = erro + ", Frequencia";
                } else {
                    try {
                        frequencia = Double.parseDouble(jTextField2.getText());
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Frequência: formato inválido");
                    }
                }
            }
            if (checkSelecionado.size() <= 0) {
                erro = erro + ", Entrada";
            }
            if (radioSelecionado < 0) {
                erro = erro + ", Saida";
            }
            if (erro.length() > 0) {
                JOptionPane.showMessageDialog(null, erro + ":\nCampo vázio ou não selecionado");
                jToggleButton1.setSelected(false);
                jToggleButton1.setText("Start");
            } else {
                desabilitaEntradaSaida();

                new Thread() {
                    public void run() {
                        while (jToggleButton1.isSelected()) {
                            if (sinalAtual == DEGRAU) {
                                if(isMalhaAberta){
                                    pv = amplitude;
                                }else{
                                    pv = 4;
                                }
                            }
                            if (sinalAtual == ONDA_SENOIDAL) {
                                if(isMalhaAberta){
                                    pv = amplitude * Math.sin(frequencia * Math.toRadians(x)) + offSet;
                                }else{
                                    pv =  Math.sin(frequencia * Math.toRadians(x)) + offSet;
                                }
                            }
                            if (sinalAtual == ONDA_QUADRADA) {
                                if(isMalhaAberta){
                                    pv = amplitude * ondaQuadrada(frequencia * Math.toRadians(x)) + offSet;
                                }else{
                                    pv =  ondaQuadrada(frequencia * Math.toRadians(x)) + offSet;
                                }
                            }
                            if (sinalAtual == DENTE_DE_SERRA) {
                                if(isMalhaAberta){
                                    pv = amplitude * denteDeSerra(frequencia * Math.toRadians(x));
                                }else{
                                    pv = denteDeSerra(frequencia * Math.toRadians(x));
                                }
                            }
                            if (sinalAtual == SINAL_ALEATORIO) {

                            }
                            long tempoInicial = System.currentTimeMillis();
                            if (isMalhaAberta) {
                                try {
                                    //leitura
                                    tensaoTanque1 = qClient.read(0);
                                    tensaoTanque2 = qClient.read(1);
                                    //calculos
                                    nivelTanque1 = tensaoTanque1 * 6.25;
                                    nivelTanque2 = tensaoTanque2 * 6.25;
                                    //travas
                                    if (tensaoTanque1 > 4) {
                                        pv = 4;
                                    }
                                    if (tensaoTanque1 < -4) {
                                        pv = -4;
                                    }
                                    if (nivelTanque1 < 3 && tensaoTanque1 < 0) {
                                        pv = 0;
                                    }
                                    if (nivelTanque1 > 28 && tensaoTanque1 > 3.25) {
                                        pv = 3.25;
                                    }
                                    if (nivelTanque1 > 29 && tensaoTanque1 > 0) {
                                        pv = 0;
                                    }
                                    //escrita
                                    qClient.write(0, pv);
                                } catch (QuanserClientException ex) {
                                    JOptionPane.showMessageDialog(null, "Erro de I/O");
                                }
                            }
                            if (!isMalhaAberta) {
                                try {
                                    //leitura
                                    tensaoTanque1 = qClient.read(0);
                                    tensaoTanque2 = qClient.read(1);
                                    //calculos
                                    nivelTanque1 = tensaoTanque1 * 6.25;
                                    nivelTanque2 = tensaoTanque2 * 6.25;
                                    
                                    //erro = sp - pv;
                                    double erro = amplitude - nivelTanque1;
                                    pv = erro/6.25;
                                    //travas
                                    if (tensaoTanque1 > 4) {
                                        pv = 4;
                                    }
                                    if (tensaoTanque1 < -4) {
                                        pv = -4;
                                    }
                                    if (nivelTanque1 < 3 && tensaoTanque1 < 0) {
                                        pv = 0;
                                    }
                                    if (nivelTanque1 > 28 && tensaoTanque1 > 3.25) {
                                        pv = 3.25;
                                    }
                                    if (nivelTanque1 > 29 && tensaoTanque1 > 0) {
                                        pv = 0;
                                    }
                                    //escrita
                                    qClient.write(0, pv);
                                } catch (QuanserClientException ex) {
                                    JOptionPane.showMessageDialog(null, "Erro de I/O");
                                }
                            }
                            long tempoFinal = System.currentTimeMillis();
                            
                            x = x + 0.1;
             
                            long resto = tempoFinal - tempoInicial;
                            if (resto < 100) {
                                try {
                                    Thread.sleep(resto);
                                    Thread.currentThread().interrupt();
                                } catch (InterruptedException ex) {
                                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            } else {
                                Thread.currentThread().interrupt();
                            }
                           
                            if(!jToggleButton1.isSelected()){
                                Thread.currentThread().interrupt();
                            }
                        }
                    }
                }.
                        start();
                criandoGrafico(0,0);
                //atualizando os niveis dos tanques
                jProgressBar1.setValue(Integer.parseInt(String.valueOf(nivelTanque1)));
                jProgressBar2.setValue(Integer.parseInt(String.valueOf(nivelTanque2)));

            }
        } else {
            jToggleButton1.setText("Start");
            habilitaEntradaSaida();
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
        //Quando o usuario digitar periodo preencher automaticamente a frequencia e vice-versa
        double frequencia = 0;
        if (jTextField2.getText().isEmpty() && jTextField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Frequencia/Periodo: Campo vazio");
        } else if (jTextField1.getText().isEmpty()) {
            //passa o numero digitado para inteiro, caso não seja um número dispara uma mensagem
            try {
                frequencia = Integer.parseInt(jTextField2.getText());
                double periodo = 1 / frequencia;
                jTextField1.setText("" + periodo);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Frequencia: Campo inválido");
                jTextField2.setText("");
            }

        }
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        int periodo = 0;
        if (jTextField1.getText().isEmpty() && jTextField2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Frequencia/Periodo: Campo vazio");
        } else if (jTextField2.getText().isEmpty()) {
            //passa o numero digitado para inteiro, caso não seja um número dispara uma mensagem
            try {
                periodo = Integer.parseInt(jTextField1.getText());
                double frequencia = 1 / periodo;
                jTextField2.setText("" + frequencia);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Periodo: Campo inválido");
                jTextField1.setText("");
            }

        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        // TODO add your handling code here:
        //verifica se está vazio
        if (jTextField3.getText().isEmpty()) {
            jTextField3.setText("0");
        } else {
            //caso não , verifica se é um numero
            try {
                offSet = Integer.parseInt(jTextField3.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Offset: Campo inválido");
                offSet = 0;
            }
        }
    }//GEN-LAST:event_jTextField3FocusLost
    public void desabilitaEntradaSaida() {
        jRadioButton1.setEnabled(false);
        jRadioButton2.setEnabled(false);
        jRadioButton3.setEnabled(false);
        jRadioButton4.setEnabled(false);
        jRadioButton5.setEnabled(false);
        jRadioButton6.setEnabled(false);
        jRadioButton7.setEnabled(false);
        jRadioButton8.setEnabled(false);
        jRadioButton9.setEnabled(false);
        jRadioButton10.setEnabled(false);
        jRadioButton11.setEnabled(false);
        jRadioButton12.setEnabled(false);
        jRadioButton13.setEnabled(false);
        jRadioButton14.setEnabled(false);
        jCheckBox1.setEnabled(false);
        jCheckBox2.setEnabled(false);
        jCheckBox3.setEnabled(false);
        jCheckBox4.setEnabled(false);
        jCheckBox5.setEnabled(false);
        jCheckBox6.setEnabled(false);
        jCheckBox7.setEnabled(false);
        jSpinner1.setEnabled(false);
        jSpinner2.setEnabled(false);
        jSpinner3.setEnabled(false);
        jSpinner4.setEnabled(false);
        jSpinner5.setEnabled(false);
        jTextField1.setEnabled(false);
        jTextField2.setEnabled(false);
        jTextField3.setEnabled(false);
    }

    public void habilitaEntradaSaida() {
        jRadioButton1.setEnabled(true);
        jRadioButton2.setEnabled(true);
        jRadioButton3.setEnabled(true);
        jRadioButton4.setEnabled(true);
        jRadioButton5.setEnabled(true);
        jRadioButton6.setEnabled(true);
        jRadioButton7.setEnabled(true);
        jRadioButton8.setEnabled(true);
        jRadioButton9.setEnabled(true);
        jRadioButton10.setEnabled(true);
        jRadioButton11.setEnabled(true);
        jRadioButton12.setEnabled(true);
        jRadioButton13.setEnabled(true);
        jRadioButton14.setEnabled(true);
        jCheckBox1.setEnabled(true);
        jCheckBox2.setEnabled(true);
        jCheckBox3.setEnabled(true);
        jCheckBox4.setEnabled(true);
        jCheckBox5.setEnabled(true);
        jCheckBox6.setEnabled(true);
        jCheckBox7.setEnabled(true);
        jSpinner1.setEnabled(true);
        jSpinner2.setEnabled(true);
        jSpinner3.setEnabled(true);
        jSpinner4.setEnabled(true);
        jSpinner5.setEnabled(true);
        jTextField1.setEnabled(true);
        jTextField2.setEnabled(true);
        jTextField3.setEnabled(true);

    }
    //Classe responsável pela thread que irá coletar os dados
/*Não precisou
    public class ThreadDados extends Thread {

        double pv;

        public ThreadDados(double pv) {
            this.pv = pv;
        }

        @Override
        public void run() {
            long tempoInicial = System.currentTimeMillis();
            if (isMalhaAberta) {
                try {
                    //leitura
                    double tensaoTanque1 = qClient.read(0);
                    double tensaoTanque2 = qClient.read(1);
                    //calculos
                    double nivelTanque1 = tensaoTanque1 * 6.25;
                    double nivelTanque2 = tensaoTanque2 * 6.25;
                    //travas
                    if (tensaoTanque1 > 4) {
                        pv = 4;
                    }
                    if (tensaoTanque1 < -4) {
                        pv = -4;
                    }
                    if (nivelTanque1 < 3 && tensaoTanque1 < 0) {
                        pv = 0;
                    }
                    if (nivelTanque1 > 28 && tensaoTanque1 > 3.25) {
                        pv = 3.25;
                    }
                    if (nivelTanque1 > 29 && tensaoTanque1 > 0) {
                        pv = 0;
                    }
                    //escrita
                    qClient.write(0, pv);
                } catch (QuanserClientException ex) {
                    JOptionPane.showMessageDialog(null, "Erro de I/O");
                }
            }
            if (!isMalhaAberta) {
                try {
                    //leitura
                    double tensaoTanque1 = qClient.read(0);
                    double tensaoTanque2 = qClient.read(1);
                    //calculos
                    double nivelTanque1 = tensaoTanque1 * 6.25;
                    double nivelTanque2 = tensaoTanque2 * 6.25;
                    //travas
                    if (tensaoTanque1 > 4) {
                        pv = 4;
                    }
                    if (tensaoTanque1 < -4) {
                        pv = -4;
                    }
                    if (nivelTanque1 < 3 && tensaoTanque1 < 0) {
                        pv = 0;
                    }
                    if (nivelTanque1 > 28 && tensaoTanque1 > 3.25) {
                        pv = 3.25;
                    }
                    if (nivelTanque1 > 29 && tensaoTanque1 > 0) {
                        pv = 0;
                    }
                    //erro = sinal desejado - sinal lido
                    double erro = pv - tensaoTanque1;
                    //escrita
                    qClient.write(0, erro);
                } catch (QuanserClientException ex) {
                    JOptionPane.showMessageDialog(null, "Erro de I/O");
                }
            }
            long tempoFinal = System.currentTimeMillis();
            long resto = tempoFinal - tempoInicial;
            if (resto < 100) {
                try {
                    Thread.sleep(resto);
                    Thread.currentThread().interrupt();
                } catch (InterruptedException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                Thread.currentThread().interrupt();
            }
        }
    }
    */

    private void criandoGrafico(double xLido, double yLido) {
        //dados do gráfico
        //esses dados serão oriundos das leitura das threads
        //gráficos ideais
        new Thread() {
            @Override
            public void run() {
                while (jToggleButton1.isSelected() && sinalAtual == DEGRAU) {
                    if(isMalhaAberta){
                        series.add(x, amplitude);
                    }else{
                        series.add(x, amplitude/6.25);
                    }
                }
                while (jToggleButton1.isSelected() && sinalAtual == ONDA_SENOIDAL) {
                    double a = Math.toRadians(x);
                    if(isMalhaAberta){
                        series.add(x, amplitude * Math.sin(a * frequencia));
                    }else{
                        series.add(x, (amplitude/6.25) * Math.sin(a * frequencia));
                    }
                }
                while (jToggleButton1.isSelected() && sinalAtual == ONDA_QUADRADA) {
                    if(isMalhaAberta){
                        series.add(x, amplitude * ondaQuadrada(Math.toRadians(x) * frequencia));
                    }else{
                        series.add(x, (amplitude/6.25) * ondaQuadrada(Math.toRadians(x) * frequencia));
                    }
                }
                while (jToggleButton1.isSelected() && sinalAtual == DENTE_DE_SERRA) {
                    series.add(x, denteDeSerra(x * frequencia));
                }
                while (jToggleButton1.isSelected() && sinalAtual == SINAL_ALEATORIO) {
                    //não sei.
                    //series.add(x++, 10);
                }
            }
        }.start();
        XYSeriesCollection dados = new XYSeriesCollection(series);
        //criando um gráfico linear
        JFreeChart chart = ChartFactory.createXYLineChart("", "x", "y", dados);
        ChartPanel chartPanel = new ChartPanel(chart);
        //adicionando a frame
        jPanel7.add(chartPanel, BorderLayout.CENTER);
        chartPanel.setSize(445, 400);
        chartPanel.setVisible(true);
    }

    private double ondaQuadrada(double x) {
        return Math.signum(Math.sin(2 * Math.PI * x / 60));
    }

    private double denteDeSerra(double x) {
        return Math.asin(Math.sin(1 * 2 * Math.PI * x / 60));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupMalha;
    private javax.swing.ButtonGroup buttonGroupRadioButton;
    private javax.swing.ButtonGroup buttonGroupTipoOnda;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
